title: HollyHumphries
description: A website with a blog
header_text: ""
footer_text: Copyright 2020 Holly Humphries-Tsioumi
header_feature_image: ../uploads/img_2837.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: travelpublications
    siteurl: https://travelpublications.netlify.app
