title: TypeFace.
description: A website with a blog
header_text: ""
footer_text: Copyright 2020 Holly Humphries-Tsioumi
header_feature_image: ../uploads/untitled-design-3.png
bannerheight: 100vh
logo: ../uploads/brown-grooming-experts-beauty-logo-6.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: "About me "
    siteurl: /aboutme/
    tab: true
